services:
  postgres:
    image: 'postgres:latest'
    container_name: 'bank_postgres'
    environment:
      - 'POSTGRES_DB=bank_db'
      - 'POSTGRES_PASSWORD=postgresql'
      - 'POSTGRES_USER=postgresql'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
volumes:
  postgres_data:
